services:
  mariadb:
    image: mariadb:11.6.2
    environment:
      MARIADB_ROOT_PASSWORD: rootpassword
      MARIADB_DATABASE: generic
      MARIADB_USER: rami
      MARIADB_PASSWORD: rami
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mariadb
    healthcheck:
      test:
      - ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      - interval: 30s
      - timeout: 10s
      - retries: 5


  app:
    container_name: generic
    build:
      context: .
      dockerfile: Dockerfile-Distroless
    environment:
      SPRING_PROFILES_ACTIVE: mariadb
      SPRING_DATASOURCE_URL: jdbc:mariadb://mariadb:5432/generic
      SPRING_DATASOURCE_USERNAME: rami
      SPRING_DATASOURCE_PASSWORD: rami
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  mariadb_data: