FROM openjdk:17-slim AS build
RUN apt-get update && apt-get install -y maven && apt-get clean
WORKDIR /app
COPY . /app
RUN mvn clean package -DskipTests
FROM gcr.io/distroless/java17
WORKDIR /app
COPY --from=build /app/target/*.jar /app/app.jar
COPY /.tel/opentelemetry-javaagent.jar /app/opentelemetry-javaagent.jar
ENTRYPOINT ["java", "-javaagent:/app/opentelemetry-javaagent.jar", "-Dotel.exporter.otlp.endpoint=http://otel-collector:4318", "-Dotel.resource.attributes=service.name=accounts-app", "-jar", "/app/app.jar"]